# https://www.balena.io/docs/learn/welcome/primer/
# https://www.balena.io/docs/learn/deploy/deployment/
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
# https://docs.docker.com/engine/reference/builder/
# https://www.balena.io/docs/reference/base-images/base-images/
# https://www.balena.io/docs/learn/develop/dockerfile/
# balenalib/raspberry-pi-debian-openjdk:latest-buster-build
FROM balenalib/%%BALENA_MACHINE_NAME%%:build

RUN install_packages php unzip wiringpi

# RUN sed -i 's/;extension=gd2/extension=gd2/g' /etc/php/7.3/apache2/php.ini

RUN git clone https://github.com/grimpirate/e-Paper

WORKDIR e-Paper

# RUN wget --quiet https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip; \
# unzip ngrok-stable-linux-arm.zip; \
# rm ngrok-stable-linux-arm.zip;

RUN mkdir bin; \
make; \
rm -rf bin/ .git/ examples/ lib/ Dockerfile.template Makefile;

ENTRYPOINT /usr/bin/tvservice -o && cd php && php -S localhost:80 index.php 
